//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaXMS.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public string Nombres { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Password { get; set; }
        public string Username { get; set; }
        public int PaisId { get; set; }
        public System.Guid Id { get; set; }
    
        public virtual Pais Pais { get; set; }
    }
}
